# Generated by Django 5.0.6 on 2024-06-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
