# Generated by Django 5.0.6 on 2024-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ingrediente_nombre_alter_ingrediente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ingredientes',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Formato: - Ingrediente 1\n- Ingrediente 2, etc.', null=True),
        ),
    ]
