# Generated by Django 5.0.6 on 2024-06-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
