# Generated by Django 5.0.6 on 2024-06-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_suscripcion_disponible_suscripcion_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
