# Generated by Django 5.0.6 on 2024-06-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_suscripcion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
